### ISSUE TITLE
Реорганизация обложек в папке

### ISSUE THREAD

**Issue by furtivite** [doka-guide/content#1503]
Сейчас некоторые обложки лежат в виде файла `cover.png` в каталоге `images` (старая схема), а другие по новой схеме: `images/covers/desktop.(png/svg)` - которая позволяет положить рядом несколько размеров и в дальнейшем добавить картинки для социальных сетей и OG. 

Для единообразия (и дальнейшей настройки платформы), стоит перенести картинки по новому принципу и добавить альтернативные описания там, где их нет.

## Вёрстка
- [x] css/focus #1504
- [x] html/comments #1505 
- [x] html/div #1506
- [x] html/footer #1507
- [x] html/h1-h6 #1508

## JS и инструменты
- [x] js/alert #1492
- [x] js/api #1491
- [x] js/async-in-js #1493
- [x] js/bom #1512
- [x] js/closures #1513
- [x] js/code-style #1514
- [x] js/deal-with-forms #1494
- [x] js/debounce #1515
- [x] js/element-positioning-js #1516
- [x] js/how-th-browser-creates-pages #1517
- [x] js/how-to-test-and-why #1486
- [x] js/infinite-scroll #1518
- [x] js/language-versions #1519
- [x] js/objects-objects-everywhere #1520
- [x] js/oop #1521
- [x] js/programming-paradigms #1522
- [x] js/promise #1523
- [x] js/recursion #1524
- [x] js/ref-type-vs-value-type #1525
- [x] js/testing-and-fake-objects #1526
- [x] js/throttle #1527
- [x] js/try-catch #1487
- [x] js/typecasting #1528
- [x] js/web-app-works #1529
- [x] js/web-security #1490
- [x] tools/code-review #1530

**Comment by furtivite** [comment]
@solarrust и @nlopin, прошу помочь с аппрувами. Собрал тут всё.

**Comment by nlopin** [comment]
Спасибо за помощь, Егор 🖤! Один пул реквест подвис, нужен апрув на словарь

**Comment by nlopin** [comment]
Все обложки перенесены. Закрываю
